### ISSUE TITLE
AL SN Ia is not compatible with latest lightcurve functionalities

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/fink-science#438]
We currently use `actsnfink` at revision `4f46b3a1e29de45793125452974e71e92c1ea454` (1st Dec 2023). With lightcurve version 0.9.6 I get the following error:

```python
Traceback (most recent call last):
  File "/home/libs/fink-science/fink_science/random_forest_snia/processor.py", line 31, in <module>
    from actsnfink.classifier_sigmoid import get_sigmoid_features_dev
  File "/home/libs/bin/src/actsnfink/actsnfink/__init__.py", line 19, in <module>
    from actsnfink.rainbow import *
  File "/home/libs/bin/src/actsnfink/actsnfink/rainbow.py", line 21, in <module>
    from light_curve.light_curve_py import RainbowRisingFit
ImportError: cannot import name 'RainbowRisingFit' from 'light_curve.light_curve_py' (/home/libs/miniconda/lib/python3.9/site-packages/light_curve/light_curve_py/__init__.py)
```

If I upgrade `actsnfink` to the latest revision to date (`cb61bbb34630c7811862050389b0f993de9639c7`) the code goes through, but the test results are different:

```python
File "/home/libs/fink-science/fink_science/__init__.py", line ?, in __main__.rfscore_rainbow_elasticc
Failed example:
    df.filter(df['pIa'] > 0.5).count()
Expected:
    79
Got:
    29

File "/home/libs/fink-science/fink_science/__init__.py", line ?, in __main__.rfscore_rainbow_elasticc
Failed example:
    df.filter(df['pIa'] == -1.0).count()
Expected:
    153
Got:
    141
```

is that expected?

**Comment by JulienPeloton** [comment]
Upgraded actsnfink.
