### ISSUE TITLE
CDS xmatch: old module fails

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/fink-science#76]
The xmatch module using the vizier tools is failing with error

```
/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 4 raised an error (recorded in the `errors` attribute of the result table): '1:44:58.7928 -26:45:24.997': No astronomical object found :

  (error.line, error.msg))

**********************************************************************

File "fink_science/xmatch/classification_slow.py", line 142, in __main__.cross_match_alerts_raw_slow

Failed example:

    objects = cross_match_alerts_raw_slow(id, ra, dec)

Exception raised:

    Traceback (most recent call last):

      File "/opt/python/3.6.7/lib/python3.6/doctest.py", line 1330, in __run

        compileflags, 1), test.globs)

      File "<doctest __main__.cross_match_alerts_raw_slow[3]>", line 1, in <module>

        objects = cross_match_alerts_raw_slow(id, ra, dec)

      File "fink_science/xmatch/classification_slow.py", line 152, in cross_match_alerts_raw_slow

        data_new = xmatch_slow(ra, dec, oid, distmaxarcsec=1)

      File "fink_science/xmatch/classification_slow.py", line 88, in xmatch_slow

        data_new['main_id'] = data_new['main_id'].values[0].decode('ascii')

    AttributeError: 'str' object has no attribute 'decode'
```

Since we are not using it, rather than fixing it, we should remove the unused code.

**Comment by JulienPeloton** [comment]
#77
